server:
  port: 8080
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
rabbitmq:
  process:
    queue: fundQueue
    exchange: fundExchange
    routing: fund
  dlx:
    queue: dlxFundQueue
    exchange: dlxFundExchange
mybatis-plus:
  # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: cn.blogscn.fund.emuns